[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Next.js specific plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
