[build]
  command = "npm install --force && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/next"

[build.environment]
  NODE_VERSION = "18"