import { HeadLinks } from "@/components/HeadLinks";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function LoginLayout({ children }) {
  return (
    <html lang="en">
      <HeadLinks />
      <body>{children}</body>
    </html>
  );
}
