import { HeadLinks } from "@/components/HeadLinks";
import "../globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <HeadLinks />
      <body className="flex justify-center align-middle">{children}</body>
    </html>
  );
}
